### ISSUE TITLE
Add wrapper method for the PHPUnit fixture methods if not provided by WordPress

### ISSUE THREAD

**Issue by pierlon** [Yoast/wp-test-utils#14]
Currently, WordPress plugins and themes attempting to run integration tests against WP < 5.2 might fail if their test suite makes use of the polyfilled fixture methods provided by [PHPUnit-Polyfills](https://github.com/Yoast/PHPUnit-Polyfills/#testcases).

I'd like to propose adding these polyfilled fixture methods to this library as a means of fallback if they're not provided by WP.

**Comment by jrfnl** [comment]
@pierlon I've pulled PR #20 which should solve this. If you have the chance, it would be great if you could do a test run with the PR.

**Comment by pierlon** [comment]
@jrfnl It works perfectly, thank you!

**Comment by jrfnl** [comment]
@pierlon Thanks for testing! It will be included in the next release (upcoming soon).
