### ISSUE TITLE
Doesn't work with latest install-wp-tests.sh

### ISSUE THREAD

**Issue by GaryJones** [Yoast/wp-test-utils#3]
In the latest version of https://github.com/wp-cli/scaffold-command/blob/479cd4f10f638d7a46a5b4a60c80bd4b4a6bd5e2/templates/install-wp-tests.sh#L111-L112, the SVN checkout is:

```sh
svn export --quiet --ignore-externals https://develop.svn.wordpress.org/${WP_TESTS_TAG}/tests/phpunit/includes/ $WP_TESTS_DIR/includes
svn export --quiet --ignore-externals https://develop.svn.wordpress.org/${WP_TESTS_TAG}/tests/phpunit/data/ $WP_TESTS_DIR/data
```

This means that in my local WP_TESTS_DIR directory, I have an `includes/` and a `data/`. There is no `tests/phpunit/` in those paths.

However, the code [here](https://github.com/Yoast/wp-test-utils/blob/develop/src/WPIntegration/bootstrap-functions.php#L49) and elsewhere in that bootstrap functions file, look for, or assume the presence of `tests/phpunit`, which means the path lookup fails and the tests fail to run when using `bootstrap_it()`.

I've now tried to integrate wp-test-utils into two different projects, and struggled with this on both occasions. I spoke to @jrfnl and she said to raise it here :-)

**Comment by jrfnl** [comment]
Thanks for reporting this @GaryJones !

Got any suggestions on how to solve this ? Maybe recognize a separate environment variable which can be used when using the WPCLI scaffold command as a base ?

Would you like to work on a PR for this ?

**Comment by jrfnl** [comment]
Marking this as a feature request as WP Test Utils was not set up with the Scaffold Command in mind, so adding support for it that environment, would constitute a new feature.

**Comment by jrfnl** [comment]
@GaryJones I've been looking into this issue, but have not been able to set up a test environment as the `bin/install-wp-tests.sh` script which the scaffold command creates, does not work on Windows.

Purely based on looking through the code, I believe I _may_ have a simple, workable solution, but as I haven't got a working test environment, I haven't been able to confirm.

Would you mind testing the following PR to verify if this solves the issue ? https://github.com/Yoast/wp-test-utils/pull/4

**Comment by GaryJones** [comment]
@jrfnl Thanks - confirming that once I'd got my WP_TESTS_DIR and WP_PLUGIN_DIR constants defined, then yes, the removal of the extra conditional part in #4 allows the tests to run.

Here's my bootstrap file (in `plugins/wp-parsely/tests/bootstrap.php`):

<details>
<summary>bootstrap.php</summary>

```php
<?php
/**
 * PHPUnit bootstrap file
 *
 * @package wp-parsely
 */

use Yoast\WPTestUtils\WPIntegration;

// GJ: This check and condition are extra to what is in the wp-test-utils readme.
$_tests_dir = getenv( 'WP_TESTS_DIR' );
if ( ! $_tests_dir ) {
	$_tests_dir = rtrim( sys_get_temp_dir(), '/\\' ) . '/wordpress-tests-lib';
	putenv( 'WP_TESTS_DIR=' . $_tests_dir );
}

if ( getenv( 'WP_PLUGIN_DIR' ) !== false ) {
	define( 'WP_PLUGIN_DIR', getenv( 'WP_PLUGIN_DIR' ) );
} else { // GJ: This else is also extra.
	$_plugin_dir = dirname( dirname( __DIR__ ) );
	define( 'WP_PLUGIN_DIR', $_plugin_dir );
	putenv( 'WP_PLUGIN_DIR=' . $_plugin_dir );
}

$GLOBALS['wp_tests_options'] = [
	'active_plugins' => [ 'wp-parsely/wp-parsely.php' ],
];

require_once dirname( __DIR__ ) . '/vendor/yoast/wp-test-utils/src/WPIntegration/bootstrap-functions.php';

/*
 * Load WordPress, which will load the Composer autoload file, and load the MockObject autoloader after that.
 */
WPIntegration\bootstrap_it();

if ( ! defined( 'WP_PLUGIN_DIR' ) || file_exists( WP_PLUGIN_DIR . '/wp-parsely/wp-parsely.php' ) === false ) {
	echo PHP_EOL, 'ERROR: Please check whether the WP_PLUGIN_DIR environment variable is set and set to the correct value. The unit test suite won\'t be able to run without it.', PHP_EOL;
	exit( 1 );
}

// Include the Parsely custom test cases.
require_once __DIR__ . '/testcase.php';
require_once __DIR__ . '/structured-data/class-non-post-testcase.php';
```

</details>

**Comment by jrfnl** [comment]
@GaryJones Thanks for testing the PR and for sharing the bootstrap file you use. This will be useful to point other people to if people have questions about implementing WP Test Utils.

I've now merged the PR and expect to tag a release some time over the next week or so (once I finish off some changes to the Polyfills repo and have released a new version of that).
