### ISSUE TITLE
Unit testing ajax methods

### ISSUE THREAD

**Issue by anver** [Yoast/wp-test-utils#32]
I've setup a docker container for my unit tests and I was able to unit test successfully using this package, can i run WP_Ajax_UnitTestCase to test ajax tests ?

**Comment by anver** [comment]
I'm using PHP 8.1.3 on the alpine container and WordPress 5.6.1 FYI

**Comment by jrfnl** [comment]
@anver I don't see any reason why you wouldn't be able to run ajax tests.

However, I do see another (BIG) problem with that setup... and that's that you are running WP 5.6 on PHP 8.1.3, which is not a good combination, let alone a supported one.

WP 5.6 is the first WP version with preliminary (beta) support for PHP 8.0.
WP 5.9 is the first WP version with preliminary (beta) support for PHP 8.1.

Neither PHP 8.0 nor PHP 8.1 are fully supported yet by WP, though generally speaking you should be able to get by with what's there, but only when running with the right PHP/WP combinations.

Does that help ?

Refs:
* https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
* https://make.wordpress.org/core/handbook/references/phpunit-compatibility-and-wordpress-versions/

**Comment by jrfnl** [comment]
Closing for lack of response.
