### ISSUE TITLE
Flushing permalink structure in a test

### ISSUE THREAD

**Issue by dingo-d** [Yoast/wp-test-utils#34]
In my tests, I'm using the `Yoast\WPTestUtils\BrainMonkey\TestCase` as my base test case (which is the point of the package 😄), but I'm a bit confused about how can I use things like `set_permalink_structure` helper in my test.

When extending the `WP_UnitTestCase` it has all these helpers in the abstract class (the permalink method is [here](https://github.com/WordPress/wordpress-develop/blob/029bea45b0c020d8eb39ea4868471238fbc46136/tests/phpunit/includes/abstract-testcase.php#L1290)).

What I did in my test is just manually do the same as this method is doing, but I feel like I'm missing something. 

I tried using [`TestCase`](https://github.com/Yoast/wp-test-utils/blob/develop/src/WPIntegration/TestCase.php) but the issue is that both [no polyfill](https://github.com/Yoast/wp-test-utils/blob/develop/src/WPIntegration/TestCaseNoPolyfills.php) one and this one have the same name, so I'm getting errors.

Any help is appreciated 🙂

**Comment by jrfnl** [comment]
> if I was to create my own custom test class extending the Yoast\WPTestUtils\WPIntegration\TestCase, using autoloading it's not clear which class I should use (from TestCase.php or TestCaseNoPolyfills.php file), as they are named the same (not sure if that's intended or not).

It's 100% intended, That's the whole point of those test cases. The correct version of the class will be included via the bootstrap utilities. Those two classes using the same name, means that child classes can safely extend the `Yoast\WPTestUtils\WPIntegration\TestCase` class and will get served the correct one based on the WP version being used.

I'm not familiar with the wiring for Pest, so I can't say anything about the implementation details of that.

**Comment by dingo-d** [comment]
Hmmm, I think I should then try to see how to use the `bootrstrap-functions.php` in my setup to correctly get the desired results (I think I tried including it, but I got some errors).

Will look into it a bit more in depth. Thanks!

**Comment by jrfnl** [comment]
@dingo-d Have a look at the readme for some examples: https://github.com/Yoast/wp-test-utils#bootstrap-utility-functions-and-custom-autoloader

The Readme also contains the explanation of what the integration test `TestCase` and the bootstrap utilities solve.
