### ISSUE TITLE
Making Yoast\WPTestUtils\WPIntegration\TestCase compatible with Pest

### ISSUE THREAD

**Issue by dingo-d** [Yoast/wp-test-utils#47]
This is an issue that's currently giving me some headaches 😅 

By default, [Pest](https://pestphp.com/docs/underlying-test-case) will use PHPUnit's `PHPUnit\Framework\TestCase` as a base class, which you can override by providing your own using the following syntax inside a file called `Pest.php`

```php
<?php

use Yoast\WPTestUtils\BrainMonkey\TestCase;

uses()->group('integration')->in('Integration');
uses()->group('unit')->in('Unit');

uses(TestCase::class)->in('Unit', 'Integration');
```

Here, I'm using Yoast's `TestCase` as my base class for both integration and unit tests. Which works. To an extent.

I'd like to use the correct test classes for the unit and for integration tests. As the building of the tests happens before the bootstrap is run (`Pest.php` file is executed/required before the `bootstrap.php` one), I don't have the access to the integration test case.

The problem is a bit deeper than just exposing the `namespace Yoast\WPTestUtils\WPIntegration\TestCase` to autoloader - mostly because WordPress doesn't have one. In my lib I am downloading the `wordpress-develop` repo to the `wp` folder so I tried just manually requiring the necessary files:

```php
<?php

require_once dirname(__DIR__) . '/wp/tests/phpunit/includes/phpunit-adapter-testcase.php';
require_once dirname(__DIR__) . '/wp/tests/phpunit/includes/abstract-testcase.php';
require_once dirname(__DIR__) . '/wp/tests/phpunit/includes/testcase.php';
require_once dirname(__DIR__) . '/vendor/yoast/wp-test-utils/src/WPIntegration/TestCase.php';

uses()->group('integration')->in('Integration');
uses()->group('unit')->in('Unit');

uses(TestCase::class)->in('Unit', 'Integration');
```

This however doesn't work, as upon running the tests I'm getting:

```bash
PHP Fatal error:  Access level to Yoast\WPTestUtils\WPIntegration\TestCase::set_up() must be public (as in class WP_UnitTestCase_Base) in .../wp-content/themes/theme-name/vendor/yoast/wp-test-utils/src/WPIntegration/TestCase.php on line 121
```

Even if the errors are somehow circumvented the above require statements would cause issues with how WordPress loads files (manually, without an autoloader), which would then cause fatal errors (file already loaded).

The bootstrapping process described in the readme works, I have added 

```xml
<env name="WP_TESTS_DIR" value="wp/tests/phpunit"/>
```

to `phpunit.xml`, and the

```php
	require_once dirname( __DIR__) . '/vendor/yoast/wp-test-utils/src/WPIntegration/bootstrap-functions.php';

	/*
	 * Bootstrap WordPress. This will also load the Composer autoload file, the PHPUnit Polyfills
	 * and the custom autoloader for the TestCase and the mock object classes.
	 */
	WPIntegration\bootstrap_it();
```

to the `bootstrap.php`, and that part works.

The only issue is: how to use the correct util test case for the integration tests? 

The problem with using the `Yoast\WPTestUtils\BrainMonkey\TestCase` one is that I don't have access to WordPress factories, and other WordPress utils, that usually come with regular integration tests.

Is this a solvable case for this lib? Or is it just too complicated to fit into Pest test framework?

**Comment by jrfnl** [comment]
Primarily this sounds like a problem with Pest not with this framework and as I don't know how Pest works, I'd suggest asking there.

Having said that, I do see one thing which may be solvable via some conditions:

> ```php
> <?php
> 
> require_once dirname(__DIR__) . '/wp/tests/phpunit/includes/phpunit-adapter-testcase.php';
> require_once dirname(__DIR__) . '/wp/tests/phpunit/includes/abstract-testcase.php';
> require_once dirname(__DIR__) . '/wp/tests/phpunit/includes/testcase.php';
> require_once dirname(__DIR__) . '/vendor/yoast/wp-test-utils/src/WPIntegration/TestCase.php';
> ```

The `'/vendor/yoast/wp-test-utils/src/WPIntegration/TestCase.php'` file is only intended for use with older WP versions. For more recent WP versions, the `'/vendor/yoast/wp-test-utils/src/WPIntegration/TestCaseNoPolyfills.php'` file is needed, which is exactly the kind of thing the registration of the autoloader in the test bootstrap would normally sort out.

The `TestCase.php` file should only be used with integration tests against WP:
```
 * - WP < 5.2;
 * - WP 5.2.0 - 5.2.12;
 * - WP 5.3.0 - 5.3.9;
 * - WP 5.4.0 - 5.4.7;
 * - WP 5.5.0 - 5.5.6;
 * - WP 5.6.0 - 5.6.5;
 * - WP 5.7.0 - 5.7.3;
 * - WP 5.8.0 - 5.8.1.
```

In all other cases, the `TestCaseNoPolyfills.php` file should be used.

Does that help ?

**Comment by dingo-d** [comment]
Thanks for the info on `TestCaseNoPolyfill`, wasn't aware when that gets used. It does solve some of the problems. The loading order is something I doubt I can change.

I guess there Is just too much incompatibility between Pest and how WordPress test suite is built. I doubt they'll do anything at their end, seeing how v2 will be a bigger rewrite.

**Comment by jrfnl** [comment]
Ha, nice! While it may not be pretty, at least you got it working, so I count that as a win ;-)

**Comment by dingo-d** [comment]
Yup, I'll need to modify my lib a bit so that things are correctly bootstrapped using the test utils, and add a readme about writing integration tests 🙂 

The `TestCaseNoPolyfill` info did help a lot 👍🏼

**Comment by jrfnl** [comment]
Well, loading the correct TestCase for WP Integration tests is the "magic" this library provides... You may want to have another read through of the README file for this package, cause it does kind of explain this.
